[package]
name = "runner-revm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
hex = "0.4"
revm = { version = "27.0.3", default-features = false, features = ["std"] }

